"""initial schema

Revision ID: 61312552e200
Revises: 
Create Date: 2025-12-19 17:15:43.577087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61312552e200'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('ticker_symbol', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('trade_action', sa.String(length=4), nullable=True),
    sa.Column('last_updated_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_uuid'), 'orders', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_uuid'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
