"""Updated order table

Revision ID: a7f9777c94c7
Revises: 
Create Date: 2025-12-06 05:37:44.089886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f9777c94c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('last_updated_time', sa.TIMESTAMP(), nullable=True))
    op.add_column('orders', sa.Column('created_time', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'created_time')
    op.drop_column('orders', 'last_updated_time')
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
