"""Updated order table timestamps.

Revision ID: c729b59f57ab
Revises: 61312552e200
Create Date: 2026-01-06 19:22:56.546753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c729b59f57ab'
down_revision: Union[str, None] = '61312552e200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('last_updated_timestamp', sa.TIMESTAMP(), nullable=True))
    op.add_column('orders', sa.Column('created_timestamp', sa.TIMESTAMP(), nullable=True))
    op.drop_column('orders', 'created_time')
    op.drop_column('orders', 'last_updated_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('last_updated_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('created_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'created_timestamp')
    op.drop_column('orders', 'last_updated_timestamp')
    # ### end Alembic commands ###
